import React from 'react'
import '../Styles/Columns.css'

const Columns = () => {
    return (
        <div className="conatiner">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima consequuntur deserunt vitae, dolorem vel suscipit inventore qui, voluptatibus consectetur facere id beatae expedita dolor atque pariatur aut repellat culpa. Possimus?
            Quae quis facilis eaque! Facere officiis provident delectus ut ex! In veritatis possimus sed, nobis vitae voluptates rem ratione. Praesentium perspiciatis ab modi, ad voluptates reiciendis nemo quibusdam iure fugit!
            Facere suscipit voluptatum illum quidem fugiat aliquam quisquam atque sint vel ad in, cupiditate quia id reprehenderit tempora aperiam modi quo quibusdam earum? Distinctio saepe, est velit deserunt quisquam alias.
            Aperiam temporibus quaerat voluptatem fugit alias nesciunt tenetur ut delectus a vitae repellendus, ipsa ab doloribus, eveniet, labore voluptatum sed adipisci. Ipsa nulla corporis similique explicabo impedit vitae, numquam veniam.
            Voluptate earum tempore beatae explicabo voluptates quam deleniti rerum libero. Perspiciatis blanditiis nihil, quibusdam laboriosam laborum itaque odit, nobis asperiores possimus quo, incidunt placeat numquam dolores suscipit obcaecati quidem ea.
            Perferendis numquam voluptas minima praesentium cum perspiciatis non cupiditate illo corrupti eius, veniam architecto ad ipsum hic earum temporibus provident delectus commodi aspernatur voluptatibus unde doloremque ea, officiis aliquam. Nam.
            Temporibus deleniti, iste officia magnam porro placeat eaque neque consequatur quae. Maiores illo harum molestias sed porro dolorum cupiditate architecto exercitationem recusandae velit, mollitia quasi numquam sequi eaque quas dignissimos.
            Inventore iure, corporis tenetur laudantium pariatur iusto ratione, veritatis tempora vel culpa similique iste reiciendis ullam. Molestiae, tempore dolorem? Sequi impedit labore omnis quos delectus possimus autem quod amet quisquam?
            Commodi omnis saepe modi, deserunt, autem nobis nulla tenetur dignissimos veritatis expedita velit repudiandae ipsum? Reiciendis, facilis sunt ut iste fuga vero atque dolore autem aspernatur eos, iure sapiente saepe?
            Quas, et laudantium sint iusto quisquam provident culpa fugit nostrum molestias libero expedita. Nisi possimus nesciunt vero repellendus! Aliquid, illo eum! Fuga numquam in libero adipisci provident assumenda minus nam!
            Sed cupiditate nulla velit optio veritatis iste voluptatem repudiandae fugiat. Placeat neque ducimus maiores deleniti, molestiae praesentium, minus voluptatibus, reprehenderit explicabo blanditiis laborum doloribus distinctio excepturi tenetur vero modi nesciunt.
            Mollitia vero quaerat laudantium ab ex natus tempore pariatur quasi. Velit ut error deserunt fugiat nobis id, officia aut dicta minima facilis odio. Tempora veniam aperiam aspernatur ullam, delectus blanditiis!
            Voluptate neque quae, sapiente ea dolores delectus minus assumenda ipsa quos tempora magnam cupiditate ex amet qui consequuntur modi. Facilis consequatur, cum excepturi quia dolores ipsa deserunt sint reprehenderit modi?
            Eius dolorem animi corrupti? In dolorum vel repellendus, autem iusto nesciunt rem culpa earum impedit ducimus inventore harum quam, veniam optio eligendi a hic qui incidunt esse asperiores officia! Eos.
            Velit omnis modi inventore corporis deserunt cumque! Blanditiis veniam corporis quo nemo qui odit maiores corrupti voluptatem adipisci hic vel, esse, sint ea id, aut officia reprehenderit! Maxime, quos unde.
            Quidem facere rerum consectetur modi tempora beatae eaque architecto recusandae? Impedit harum labore dicta, laboriosam dignissimos quaerat, dolor nihil quam, nisi odio sint cupiditate. Recusandae nihil tenetur consectetur reprehenderit voluptatum.
            Quae, omnis quidem voluptatem adipisci quaerat iure deleniti animi at illo provident laudantium facilis itaque eligendi ut iusto blanditiis quas impedit, consequuntur aliquam repellendus. Velit quae accusamus rem ab neque!
            Corrupti sed cum eius veniam, laboriosam illum dolore dolores. Culpa, facilis maiores saepe veritatis obcaecati eveniet esse libero nisi tempora ipsam? Nihil nobis iusto non alias commodi laboriosam facere nisi!
            Possimus perspiciatis veniam porro quas fuga at, autem sequi! Incidunt exercitationem quos rerum ipsum, molestiae nesciunt consequatur blanditiis debitis ex, dolor deleniti. Vel iure veritatis sed. Saepe asperiores cumque maiores?
            Nulla eos accusantium provident consequuntur tenetur distinctio dolorum fuga, quidem laboriosam. Error perferendis aliquid incidunt quos, non quaerat quibusdam neque ut at consectetur nemo debitis commodi laborum facilis soluta provident!
            Excepturi tempora, reiciendis eveniet nostrum, non quo molestiae dolor similique velit corrupti sequi nesciunt, commodi quas molestias perferendis voluptates obcaecati minima quod ipsa repudiandae eaque? Quisquam ad omnis nostrum modi.
            Laborum, saepe ad! Odio cumque ab porro eveniet quaerat voluptatem magnam eum maxime nesciunt ut facere dolorum dolor officiis error, officia numquam a. Laboriosam ullam, atque aut ipsam sint quod!
            Aspernatur voluptatibus possimus earum distinctio esse debitis id velit consequatur corrupti architecto! Reprehenderit dolor earum omnis quam similique. Aut accusantium adipisci earum quia blanditiis magnam suscipit culpa eaque vitae quae!
            Doloremque molestiae reprehenderit quis voluptates illo cupiditate. Itaque minus magnam error necessitatibus perferendis aut dolores commodi, odio suscipit sapiente soluta eum quam impedit cum similique aperiam cupiditate expedita qui at.
            Tempore doloribus iure atque ad, animi ullam illo aperiam provident optio. Beatae quam ipsam sequi amet possimus, reiciendis doloribus ipsa porro laborum vero, accusantium quisquam quo veritatis sunt minus iusto?
            Porro praesentium minus officia animi possimus aperiam neque vel aliquam. Sit, ratione tempora aut pariatur doloremque voluptatibus sint repellat accusantium corporis. Omnis labore at consectetur modi atque facere. Quia, porro.
            Ratione, rerum necessitatibus quas, doloremque laborum at quos illum amet voluptate iste nam natus ab enim quibusdam distinctio facilis, odio velit voluptatum? Provident quidem placeat eos, architecto qui ipsam in!
            Consequatur repellendus, nobis ea molestiae et laudantium saepe dolorem rerum odio quaerat velit, praesentium, amet recusandae alias laboriosam! Ipsum, amet molestiae illum fugiat aut obcaecati quasi optio quod voluptate quisquam.
            Molestiae ratione nesciunt neque consequuntur quas? Officia, sunt cupiditate, ipsam minus corrupti veniam mollitia tempora, molestias voluptate blanditiis facere recusandae. Exercitationem, doloremque. Natus tempore commodi dolore architecto perspiciatis hic assumenda.
            Tempore eos officia facilis obcaecati earum nesciunt. Expedita sint officiis vitae quam id odit alias quisquam amet ipsa obcaecati quo eligendi eaque illum porro culpa magnam nesciunt iusto, excepturi nulla!
            Tempore sequi itaque consectetur nostrum in dolor odio cupiditate enim nisi commodi inventore quae autem voluptate dicta earum dolore minima accusantium, maiores adipisci, id molestiae voluptatum officia nemo. Numquam, esse!
            Ea laborum harum earum totam perspiciatis illo iusto possimus. Est aperiam voluptates dignissimos expedita doloribus commodi, quam aliquid, minima delectus laudantium recusandae culpa molestiae, eius aspernatur neque error enim? Quidem?
            Nemo, ratione. Nobis excepturi quae vero qui quod vel eum neque, sint in similique doloribus distinctio delectus, quia, error nisi nihil adipisci iste eligendi molestiae aliquid tempore suscipit. Illo, sed!
            Incidunt, voluptatum. Cum consequatur, esse earum architecto dolorum consequuntur dolor, autem repellendus error nobis quia explicabo ad. Ut, quas omnis assumenda qui dolorum ullam quisquam eius eum, excepturi sunt deleniti.
            Facilis cumque provident, iure odio ducimus sapiente consequuntur ut libero voluptatibus, vel doloremque nemo? Perspiciatis maxime ipsum saepe necessitatibus enim, minus doloribus! Officia sed nulla exercitationem a, mollitia temporibus vitae?
            Veritatis delectus laboriosam ratione vel dignissimos et, accusantium, ipsa ducimus maxime nemo ullam! Maiores sed veritatis quas illum quod, explicabo culpa perferendis, quae consequatur quo ut in odit ipsum ratione?
            Inventore, voluptatibus quia nulla totam ut, molestias saepe accusantium dolore voluptate sapiente dolorem asperiores laudantium iure? Delectus illo earum necessitatibus facere sint eos, nihil non soluta exercitationem quam, accusantium iste.
            Doloremque qui, sapiente fuga, voluptatibus culpa aliquam omnis quo eos numquam nostrum atque delectus inventore, alias ducimus repellendus. Dolorum doloribus neque veniam id aspernatur eius vitae perferendis nam soluta assumenda.
            Voluptatem, sunt, ratione vero reprehenderit beatae voluptate nesciunt ipsam impedit quos provident saepe, asperiores incidunt. Nostrum, et necessitatibus! Perspiciatis iusto, veniam beatae quam rerum tempora adipisci dolorem et provident nam.
            Assumenda quod eum, et blanditiis consequuntur dolor recusandae libero eius impedit voluptas perspiciatis. Molestias velit repellendus eligendi aut, nemo iste illo dicta hic rem ipsam pariatur animi inventore quis culpa.
            A, nihil! Aut illum ipsum, temporibus quam amet iusto, nihil unde sapiente id commodi hic. Aliquid dolores fugiat exercitationem sunt modi asperiores corrupti consectetur! Possimus, ducimus. Exercitationem accusamus ipsa repudiandae!
            Praesentium ipsam commodi dolorem. Corporis eveniet atque vel odio suscipit! Modi possimus magnam repellat veniam ad nesciunt accusamus, vitae esse quos laboriosam explicabo quaerat, necessitatibus, suscipit aspernatur animi nam ducimus.
            Ut reiciendis repellendus sed nemo veniam non eveniet atque sapiente excepturi culpa labore dolore numquam mollitia maiores deleniti, ex enim quisquam! Autem ipsa molestiae obcaecati nihil tenetur et modi at.
            Rerum magnam molestias cumque tempora vel error omnis sint aperiam odio harum ab eos, doloribus neque, unde totam perspiciatis veritatis quaerat perferendis aliquid? Officiis et tenetur error neque quidem. Quae?
            Illum, officia dolor, quod unde nulla cupiditate illo, deleniti officiis sed quam voluptates saepe debitis rem eum qui nesciunt quidem rerum excepturi! Deleniti explicabo cumque ad assumenda ullam non earum.
            Deleniti est, adipisci minima sequi impedit aliquam odio recusandae a assumenda facere porro ducimus ullam iure quis non libero nulla eum asperiores repudiandae sed? Accusantium, nisi? Minima libero est dolore!
            Soluta perspiciatis necessitatibus quas ipsam voluptate nihil, repellat perferendis dolorum, molestiae asperiores itaque officia inventore debitis. Illo, voluptate inventore! Id vitae, rem sunt impedit dolores fuga nisi itaque repellat similique.
            Qui, aperiam vitae? Ex cumque repellendus eius explicabo reprehenderit nostrum voluptas architecto natus optio magni nihil, libero voluptates. Eveniet repudiandae harum maiores rerum error ratione, et accusamus maxime inventore iusto.
            Officia libero praesentium illum cumque asperiores tempore assumenda nesciunt reiciendis ratione optio, facere recusandae accusantium est fugit dolores quod voluptatum aliquid pariatur ex. Nobis iure doloremque magnam atque quia debitis?
            Voluptas dolor totam inventore, at debitis obcaecati beatae eos facere voluptatum ratione soluta vero, ducimus nobis cupiditate sequi omnis repellendus quam laudantium provident quidem! Nemo ex magnam veritatis nisi animi.
            Earum vel deleniti aliquid consectetur officiis sapiente quia, adipisci labore totam sed sequi beatae doloremque explicabo et maiores quas, neque deserunt? Minus quibusdam corrupti consectetur aperiam officia autem quod eum.
            Asperiores quasi odit itaque officiis laboriosam ex eum blanditiis dicta deleniti! Reprehenderit quisquam placeat, molestiae harum officiis dolorem dicta ullam fugiat perspiciatis vel vero quasi dignissimos itaque, laborum magnam culpa.
            Vel commodi non dignissimos quas eligendi. Asperiores commodi minus error dolore, illum voluptatibus hic dolores molestiae voluptas reprehenderit nam necessitatibus reiciendis expedita doloremque libero magnam rem fugiat explicabo nulla repellat.
            Laborum ea blanditiis provident quas excepturi eaque necessitatibus voluptates libero dicta? Ab ex eos, tempora fugit cupiditate laboriosam quos quisquam qui esse delectus veritatis facilis. Praesentium sequi dolores at ratione?
            Vel a, tenetur harum ipsum reiciendis consequatur expedita inventore iste? Qui fuga pariatur ut ipsa atque optio! Unde labore pariatur architecto harum iure? Ullam iste voluptatibus hic sapiente? Maiores, dolor.
            Ab neque maiores qui labore esse necessitatibus minus ipsa libero quas, molestiae consectetur atque laborum provident, rem vero officia commodi nesciunt! Amet laboriosam libero inventore fugit provident praesentium quia nihil.
            Provident excepturi accusamus, autem quas, aliquid laborum dolor, officia aut tenetur nihil corrupti natus delectus ad dolore mollitia. Non nihil odio natus vero, facere molestias! Repellat qui cum enim itaque.
            Veritatis sint aspernatur voluptate. Impedit, vero. Facere necessitatibus quod natus sint aspernatur consequatur, vero eos adipisci. Architecto laudantium, totam quia porro quam quaerat labore asperiores delectus, distinctio impedit, harum animi.
            Eum nemo ipsa, fugit explicabo cum aut iusto consectetur est, corporis dolor, voluptas eligendi. Rerum, repudiandae voluptate odio temporibus consequatur eligendi mollitia, distinctio sapiente est esse illum at id excepturi.
            Laudantium doloremque voluptatibus repellendus a dolor! Suscipit atque enim numquam nostrum dolor commodi ex consectetur, quidem architecto, incidunt asperiores ducimus vero necessitatibus, ut reprehenderit laboriosam rerum sapiente temporibus quo. Qui?
            Accusamus quasi adipisci dicta, labore asperiores sunt dolore dolorem ea reprehenderit mollitia. Doloremque ipsam maxime, praesentium maiores aliquid, quis magnam suscipit animi quibusdam fugit, quaerat consequatur hic obcaecati ut! Possimus.
            Accusamus pariatur mollitia id saepe dolores, repellat soluta nam vel aspernatur cum molestiae laudantium incidunt tempore. Aliquam assumenda, repellendus quibusdam asperiores ex illo fuga, dignissimos dolore sapiente dolores voluptatum cupiditate.
            Eligendi eaque id sequi non inventore, sapiente, quisquam possimus obcaecati quos illum incidunt saepe officiis voluptatibus fugiat! Vero cupiditate eum, officia eveniet ipsa modi, earum quo dolores sint enim sunt.
            Blanditiis dolore ab nobis magni, nisi totam quia aut suscipit id et rem enim molestiae dicta itaque at! Nostrum eaque nesciunt nisi necessitatibus excepturi ipsam ipsa, perferendis porro est placeat.
            Minima impedit pariatur ab, vitae a, nobis laudantium odit temporibus ducimus id recusandae rem deserunt eum explicabo, saepe similique beatae! Dolorem aliquid repellat sit culpa recusandae voluptatibus nostrum, libero minima.
            Repudiandae nostrum rem amet, placeat vero vel et possimus delectus similique modi. Sunt dignissimos tempore ad incidunt sequi soluta officia, laborum debitis corrupti magnam magni accusantium earum quo, quam atque!
            Reprehenderit harum laboriosam quo laborum eum molestias doloribus repellat, minus corrupti, repellendus non nam, earum dolorem voluptas pariatur qui atque aspernatur quis! Deserunt ipsam ipsa iste blanditiis, nobis quidem vel.
            Non minus eligendi hic nulla reiciendis quam numquam in soluta id suscipit corporis, velit possimus commodi perferendis nam vitae est ducimus quos animi fuga harum veniam! Itaque nam possimus reiciendis!
            Tenetur eaque molestias voluptate voluptatibus ea earum deleniti et soluta doloremque, libero itaque reprehenderit molestiae amet obcaecati fuga iste nihil maxime quas tempora. Laborum aliquam non voluptate ullam! Omnis, dolore?
            Perspiciatis enim unde culpa est voluptatibus dolorum quam, optio explicabo in pariatur magni laboriosam vel, animi atque nam esse? Laudantium porro necessitatibus rem recusandae voluptatibus distinctio fuga. Aspernatur, cum velit.
            Voluptatibus ab molestiae excepturi quos amet architecto enim quia veritatis repellendus consequuntur deserunt voluptas debitis beatae culpa quam, aspernatur dolores aut recusandae maiores! Voluptas, quaerat voluptatibus! Soluta nobis nihil aliquid?
            Eum, quis cumque neque temporibus quidem libero maiores repellat ipsum tempore, nam natus reprehenderit nesciunt! Cum vitae nobis facere nostrum praesentium possimus culpa deleniti laudantium reiciendis voluptas, impedit enim expedita.
            Alias aperiam quasi asperiores. Explicabo illum pariatur inventore assumenda molestias magnam, blanditiis eaque obcaecati facere veritatis voluptate magni quos cumque perferendis asperiores officiis tempore consectetur, ex neque incidunt. Neque, veniam.
            Ullam voluptatem placeat eum enim fugit ab maxime tenetur aspernatur nobis ipsa doloremque sed ex ea omnis unde recusandae harum quisquam, itaque repellat. Dolor sint mollitia libero harum odit placeat?
            Id dicta sint obcaecati temporibus, earum nulla unde consequatur dolores perspiciatis cum repudiandae, quasi laborum ab distinctio? In iste, quasi itaque fugit ducimus culpa voluptate nobis, ipsum blanditiis provident molestias!
            Doloremque deserunt suscipit veritatis obcaecati. Aspernatur distinctio laborum quaerat cum rerum quae odit? Voluptatum sed, laborum, accusantium eius rem dolores dolorum eligendi est voluptatibus dolore nam obcaecati optio, unde vel.
            Optio dolore placeat odit quos, corporis sequi iusto, ducimus quasi repellat totam suscipit unde labore fugiat, incidunt doloremque dignissimos. Sed explicabo cupiditate fugit non rem quos eos aut repellat natus.
            Itaque culpa recusandae quaerat consectetur accusamus ducimus, vero nobis distinctio minima quisquam vel neque quo nemo consequuntur libero dicta minus voluptates possimus excepturi eaque! Asperiores consectetur debitis hic ipsam reprehenderit!
            Voluptatem adipisci assumenda tempore nihil, sit mollitia delectus illo vel eum corrupti quos dolorem suscipit blanditiis? Magni magnam optio maiores, eum praesentium quidem consequuntur nihil obcaecati tempore quisquam possimus nulla!
            Repellat obcaecati reprehenderit cum? Magnam, assumenda eos. Saepe sint at dicta eius hic, laboriosam vel atque corrupti rem, pariatur optio, error ipsa quasi dolor. Nobis nostrum corporis rem enim. Aliquid?
            Veniam, atque. Sit at nihil maxime odit error mollitia natus possimus enim consequatur aliquam veritatis expedita molestias pariatur velit nobis accusantium laborum, iusto nemo, praesentium eos. Perspiciatis voluptatem quae reiciendis.
            Animi veniam laboriosam error laborum rem a quidem aspernatur odit aliquid impedit ipsa molestias possimus ducimus quibusdam, perspiciatis officia inventore libero sunt nemo? Atque dicta rerum deserunt voluptatum a veniam.
            Tenetur facilis aut voluptatibus ipsum libero aspernatur numquam ea ducimus repudiandae et officia, minus reiciendis ad in, expedita incidunt vitae quaerat omnis sit voluptatem quibusdam autem? Maxime ut ab fugiat.
            Vitae placeat ratione expedita veritatis quisquam. Tempora eum vel explicabo error numquam fuga ipsa excepturi doloribus mollitia, maiores non iusto asperiores, natus earum soluta laboriosam consequuntur nesciunt! Fuga, labore inventore!
            Obcaecati nobis nostrum nemo corrupti rerum doloribus repellendus soluta aspernatur possimus, doloremque cum quasi ipsa eius suscipit ipsam tenetur qui placeat. Maiores ipsa veritatis debitis modi qui eius molestiae tempore.
            Ipsam nemo quibusdam modi culpa. Quos laudantium atque ab ex laboriosam unde, ipsum consequuntur dolore non culpa ullam quibusdam. Ea iste excepturi, nostrum non necessitatibus tempora quibusdam itaque et adipisci.
            Illum corporis asperiores quae, reprehenderit veritatis temporibus impedit harum earum sint similique! Consequatur possimus accusamus, blanditiis consequuntur impedit eaque dolore molestiae, tempore, illo numquam assumenda? Laudantium blanditiis magni impedit ullam.
            Voluptatum et recusandae sint labore nulla mollitia nam esse! Laboriosam, quae quas! Libero, vero! Consequatur repellat incidunt quaerat aspernatur facere dolores earum, asperiores nemo placeat? Eveniet delectus odio repellat in?
            Ad qui repudiandae culpa maxime incidunt architecto odit assumenda commodi voluptatibus. Repudiandae similique excepturi voluptas iste ab est, veritatis obcaecati adipisci aperiam. Enim aperiam possimus illum aspernatur asperiores nihil ex.
            Rem beatae neque natus aspernatur officia veniam architecto, iste quae id? Ex beatae temporibus similique modi, numquam, debitis ratione molestias unde soluta dolorum, voluptas exercitationem minima aperiam ab reprehenderit rem!
            Enim dolorem odio molestiae necessitatibus eos distinctio ratione, nulla harum fuga laborum facere ea. Fuga, ullam nesciunt corporis dolore sit quia est voluptatum dolorem eos error harum accusantium molestiae culpa!
            Quaerat dolores repellat expedita voluptates illum voluptas, blanditiis a dolorem commodi dicta quasi minus, quae, quas accusantium facere autem. Necessitatibus est sequi molestiae voluptates numquam magni optio voluptas enim labore.
            Nihil fugit dolorum qui quam fuga neque odit mollitia quod tempora voluptatum quas inventore praesentium, beatae, culpa ipsum enim necessitatibus porro a, aliquam dignissimos. Sequi odio beatae aut suscipit praesentium!
            Iste officiis, distinctio sint quos praesentium optio dolorum sit porro rerum architecto molestias error consectetur explicabo inventore. Similique itaque, perspiciatis, nam expedita magnam obcaecati nihil corporis deserunt, at quibusdam necessitatibus!
            Molestias laborum atque fuga qui non, quam voluptatibus quas repudiandae, accusamus, veritatis totam alias maxime aspernatur nam ex esse quasi optio iste iure! Natus, minus aliquid quaerat fugiat quibusdam cumque.
            Reiciendis odio molestias assumenda architecto sunt. Veritatis assumenda magnam quis veniam. Cupiditate totam expedita quisquam nemo odio minima rerum, maiores aspernatur ut quaerat unde dolor assumenda doloremque in sunt eum.
            Aliquam, nisi iusto sunt hic officiis eveniet laboriosam beatae qui iste delectus saepe impedit accusantium repudiandae dolorum! Nostrum rem ducimus non dolorem numquam eum nemo, omnis reiciendis aut aliquid quod?
            Alias exercitationem dignissimos pariatur obcaecati quae? Quam quo id doloremque. Rerum doloremque in labore iusto, atque dolorum deserunt cupiditate quae! Dolores quaerat accusamus vitae aperiam illum dolore repellendus ab dolorum!
            Reiciendis voluptate ullam corrupti ut omnis deleniti modi voluptas ratione illum assumenda neque et numquam harum dolores inventore explicabo quidem debitis porro, repellat eum error obcaecati beatae. Excepturi, ullam quisquam.
            Deserunt, sit quisquam enim expedita laudantium odit aut id hic explicabo? Nemo dolores esse neque quisquam excepturi eum quasi optio itaque repudiandae aut vel, similique id minus, nostrum doloremque ut.
        </div >
    )
}

export default Columns