import React from 'react'
import '../Styles/Networks.css'
import { useNavigate } from 'react-router-dom'

const Networks = () => {
  const navigateOpen = useNavigate()
  return (
    <article className='Networks'>
      <p className="images-reserves">
        Some images are generated by artificial intelligence or obtained for free from <a href="https://pixabay.com/" target='_blank'>Pixabay</a>; some of them are taken by the NEI team or sourced from the official university website.
      </p>

      <div className="contact-powerby">
        <div className="contact">
          <p>77 Main Street</p>
          <p>Springfield, MA 01103</p>
          <p>Social media channels below.</p>
        </div>
        <div className="powerby">
          <h5>Power by</h5>
          <img src="https://photo-data-base.netlify.app/assets/ai.939fef3f.png" alt="" />
        </div>
      </div>

      <p className="reserve-rights">
        All rights reserved.
      </p>

      <button className="work-with-us" onClick={() => navigateOpen('/OPENPOSSITIONS')} >
        TRABAJOS
      </button>

    </article>
  )
}

export default Networks