import React from 'react'
import '../Styles/Networks.css'

const Networks = () => {
  return (
    <article className='Networks'>
      <p className="images-reserves">
        All images are generated by artificial intelligence or obtained for free from <a href="https://pixabay.com/" target='_blank'>Pixabay</a>; some of them are taken by the NEI team.
      </p>

      <div className="contact-powerby">
        <div className="contact">
          <p>Berlin, Germany</p>
          <p>Louisenstraße 77</p>
          <p>Social media channels below.</p>
        </div>
        <div className="powerby">
          <h5>Power by</h5>
          <img src="https://photo-data-base.netlify.app/assets/ai.939fef3f.png" alt="" />
        </div>
      </div>

      <p className="reserve-rights">
      All rights reserved.
      </p>

    </article>
  )
}

export default Networks