import React from 'react';
import '../Styles/Networks.css'; // Importing styles for the Networks component
import { useNavigate } from 'react-router-dom'; // Importing useNavigate hook from react-router-dom

/**
 * Component representing network information and contact details.
 * Provides information about image sources, contact details, and attribution.
 * Contains a button to navigate to job openings.
 * @returns {JSX.Element} Networks component JSX
 */
const Networks = () => {
  // Hook for navigation
  const navigateOpen = useNavigate();

  return (
    <article className='Networks'>
      {/* Paragraph about image sources */}
      <p className="images-reserves">
        Some images are generated by artificial intelligence or obtained for free from <a href="https://pixabay.com/" target='_blank'>Pixabay</a>; some of them are taken by the NEI team or sourced from the official university website.
      </p>

      {/* Contact information and attribution */}
      <div className="contact-powerby">
        <div className="contact">
          <p>77 Main Street</p>
          <p>Springfield, MA 01103</p>
          <p>Social media channels below.</p>
        </div>
        <div className="powerby">
          <h5>Power by</h5>
          <img src="https://photo-data-base.netlify.app/assets/ai.939fef3f.png" alt="" />
        </div>
      </div>

      {/* Paragraph about all rights reserved */}
      <p className="reserve-rights">
        All rights reserved.
      </p>

      {/* Button to navigate to job openings */}
      <button className="work-with-us" onClick={() => navigateOpen('/OPENPOSSITIONS')} >
        TRABAJOS
      </button>
    </article>
  );
}

export default Networks;
